default_language_version:
  python: python3.10

default_install_hook_types: [pre-push, post-merge, pre-commit, post-checkout]

files: ^challenge/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      stages: [commit]
    - id: check-ast
      stages: [commit]
    - id: check-yaml
      args: [--unsafe]
      stages: [commit]
    - id: check-added-large-files
      args: [--maxkb, "1000"]
      stages: [commit]
    - id: debug-statements
      stages: [commit]
      exclude: offerfit/_init_.py
    - id: detect-private-key
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
    - id: no-commit-to-branch
      name: "Don't commit to branches prod and staging"
      args: [--branch, main, --branch, develop]
      stages: [commit]
  # We want to run ruff before other formatters, because ruff's fixes may need additional formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.275
    hooks:
      - id: ruff
        name: "Lint and fix code using Ruff"
        args: [ --fix, --exit-non-zero-on-fix ]
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      name: "Format code using Black"
      # --preview wraps strings in code and adds few other minor improvements to base Black
      args: [--line-length, "100", --target-version, py310, --preview]
      stages: [commit]