
swagger: '2.0'
info:
  title: flight-model-api-gateway
  description: Endpoint of the flight model
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://flight-mle-doqr3mc7la-uc.a.run.app
paths:
  /health:
    get:
      description: Check if the service is up
      operationId: health-v1
      responses:
        200:
          description: OK
  /predict:
    post:
      description: Get predictions from the model
      operationId: predict-v1
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: List of flights
          schema:
            type: object
      responses:
        200:
          description: List of predictions
          schema:
            type: object
        400:
          description: Bad request.

